# - name: Add /var/jenkins dir
#   file:
#     state: directory
#     path: /var/jenkins
#     owner: jenkins
#     mode: "u=rw,g=r,o=r"

- name: Add dirs
  file:
    state: directory
    path: "{{ item.path }}"
    owner: "{{ item.owner }}"
    group: "{{ item.group }}"
    mode: "{{ item.mode }}"
  loop: "{{ directories }}"
