# - name: "Download deb key"
#   shell:
#     cmd: "curl -fsSL https://pkg.jenkins.io/debian-stable/jenkins.io.key | sudo tee   /usr/share/keyrings/jenkins-keyring.asc > /dev/null"

- name: "Add Jenkins repository key"
  apt_key:
    url: "{{ key_url }}"
    state: present

# - name: "Copy deb key"
#   shell:
#     cmd: "echo deb [signed-by=/usr/share/keyrings/jenkins-keyring.asc]   https://pkg.jenkins.io/debian-stable binary/ | sudo tee   /etc/apt/sources.list.d/jenkins.list > /dev/null"

- name: "Add Jenkins repository"
  apt_repository:
    repo: "{{ repository_entry }}"
    state: present

- name: "Install Jenkins"
  apt:
    name: jenkins
    update_cache: yes

- name: Delete /var/lib/jenkins default content
  file:
    state: absent
    path: /var/lib/jenkins/

- name: "Mount jenkins home dir volume on startup"
  lineinfile:
    dest: /etc/fstab
    state: present
    insertafter: EOF
    line: "UUID=f0230132-4864-4eea-b634-0ad7f51507c9 /var/lib/jenkins ext4 defaults,discard 0 2"