- hosts: bastion
  become: true

  roles:
  - users_with_keys

- hosts: jenkins_master
  become: true

  roles:
  - users
  - users_with_keys
  - install_java
  - install_jenkins

- hosts: jenkins_node
  become: true

  roles:
  - users
  - users_with_keys
  - install_java
  - setup_jenkins_node