- hosts: bastion
  become: true

  roles:
  - setup_bastion_host

- hosts: jenkins_master
  become: true

  roles:
  - users
  - users_with_keys

- hosts: jenkins_node
  become: true

  roles:
  - users
  - users_with_keys