- name: "Add Node.js repository key"
  apt_key:
    url: "{{ key_url }}"
    state: present

- name: "Add Node.js repository"
  apt_repository:
    repo: "{{ repository_entry }}"
    state: present

- name: "Install Node.js"
  apt:
    name: nodejs
    update_cache: yes